-- Sample data for transactiondq table
INSERT INTO transactiondq (id, account_number, transaction_amount, transaction_type, transaction_date, description, status, source, created_at, updated_at) VALUES (1, 'ACC001', 1000.00, 'DEBIT', '2024-04-11', 'Purchase at Store A', 'PROCESSED', 'REST', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO transactiondq (id, account_number, transaction_amount, transaction_type, transaction_date, description, status, source, created_at, updated_at) VALUES (2, 'ACC002', 2500.50, 'CREDIT', '2024-04-10', 'Salary Deposit', 'PROCESSED', 'KAFKA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO transactiondq (id, account_number, transaction_amount, transaction_type, transaction_date, description, status, source, created_at, updated_at) VALUES (3, 'ACC001', 500.25, 'DEBIT', '2024-04-09', 'Online Bill Payment', 'PROCESSED', 'REST', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO transactiondq (id, account_number, transaction_amount, transaction_type, transaction_date, description, status, source, created_at, updated_at) VALUES (4, 'ACC003', 1500.00, 'CREDIT', '2024-04-08', 'Refund Processing', 'PROCESSED', 'KAFKA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO transactiondq (id, account_number, transaction_amount, transaction_type, transaction_date, description, status, source, created_at, updated_at) VALUES (5, 'ACC002', 750.75, 'DEBIT', '2024-04-07', 'ATM Withdrawal', 'PROCESSED', 'REST', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO transactiondq (id, account_number, transaction_amount, transaction_type, transaction_date, description, status, source, created_at, updated_at) VALUES (6, 'ACC004', 3000.00, 'CREDIT', '2024-04-06', 'Investment Dividend', 'PROCESSED', 'KAFKA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO transactiondq (id, account_number, transaction_amount, transaction_type, transaction_date, description, status, source, created_at, updated_at) VALUES (7, 'ACC001', 200.00, 'DEBIT', '2024-04-05', 'Insurance Premium', 'PROCESSED', 'REST', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO transactiondq (id, account_number, transaction_amount, transaction_type, transaction_date, description, status, source, created_at, updated_at) VALUES (8, 'ACC003', 450.50, 'CREDIT', '2024-04-04', 'Freelance Payment', 'PROCESSED', 'KAFKA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO transactiondq (id, account_number, transaction_amount, transaction_type, transaction_date, description, status, source, created_at, updated_at) VALUES (9, 'ACC002', 1200.00, 'DEBIT', '2024-04-03', 'Restaurant Payment', 'PROCESSED', 'REST', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO transactiondq (id, account_number, transaction_amount, transaction_type, transaction_date, description, status, source, created_at, updated_at) VALUES (10, 'ACC004', 2000.00, 'CREDIT', '2024-04-02', 'Business Transfer', 'PROCESSED', 'KAFKA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

